# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import electiondata.ed.models


class Migration(migrations.Migration):

    dependencies = [
        ('ed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NominatorArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areatxt', models.CharField(max_length=80)),
                ('nominatortxt', models.CharField(max_length=80)),
                ('candidates', models.IntegerField()),
                ('number', models.IntegerField()),
                ('numberstart', models.IntegerField()),
                ('numberend', models.IntegerField()),
                ('alliancetxt', models.CharField(max_length=80, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='alliance',
            name='areatxt',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alliance',
            name='identifier',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='is_city',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='advance_pct',
            field=electiondata.ed.models.PctField(decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='advance_votes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='comparative_index',
            field=models.DecimalField(decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='elected_information',
            field=models.IntegerField(choices=[(1, b'Elected'), (2, b'Substitute'), (3, b'Not elected')], null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='electionday_pct',
            field=electiondata.ed.models.PctField(decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='electionday_votes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='position',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='total_pct',
            field=electiondata.ed.models.PctField(decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='total_votes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nominator',
            name='advance_pct',
            field=electiondata.ed.models.PctField(decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='nominator',
            name='advance_votes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nominator',
            name='electionday_pct',
            field=electiondata.ed.models.PctField(decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='nominator',
            name='electionday_votes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nominator',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='nominator',
            name='seats',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nominator',
            name='total_pct',
            field=electiondata.ed.models.PctField(decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='nominator',
            name='total_votes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nominatorresults',
            name='advance_pct',
            field=electiondata.ed.models.PctField(decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='nominatorresults',
            name='advance_votes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nominatorresults',
            name='electionday_pct',
            field=electiondata.ed.models.PctField(decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='nominatorresults',
            name='electionday_votes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nominatorresults',
            name='seats',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nominatorresults',
            name='total_pct',
            field=electiondata.ed.models.PctField(decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='nominatorresults',
            name='total_votes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='nominatorarea',
            name='alliance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nominatorareas', to='ed.Alliance'),
        ),
        migrations.AddField(
            model_name='nominatorarea',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominatorareas', to='ed.Area'),
        ),
        migrations.AddField(
            model_name='nominatorarea',
            name='nominator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominatorareas', to='ed.Nominator'),
        ),
    ]
