# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed', '0002_auto_20170402_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='candidateresults',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nominator',
            name='identifier',
            field=models.CharField(max_length=10),
        ),
    ]
